parameters:
#    ab_test.example.class: AB\Bundle\TestBundle\Example

services:
#    ab_test.example:
#        class: %ab_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
